version: '2'
services:
    angular4-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/angular4/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=angular4
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
